QUFLEET.Web/Models/AirportsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QUFLEET.Web.Models
{
    public class AirportsViewModel
    {
        public AirportsModel EditedAirport { get; set; }
        public List<AirportsModel> AirportsList { get; set; }
    }
}

QUFLEET.Web/Controllers/AirportsController.cs
using AutoMapper;
using QUFLEET.Logic;
using QUFLEET.Data;
using QUFLEET.Repository;
using QUFLEET.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QUFLEET.Web.Controllers
{
    public class AirportsController : Controller
    {
        IAirportsLogic logic;
        IMapper mapper;
        AirportsViewModel vm;

        public AirportsController()
        {
            AirportsRepository repository = new AirportsRepository();
            logic = new AirportsLogic();
            mapper = MapperFactory.CreateMapper();
            vm = new AirportsViewModel();
            vm.EditedAirport = new AirportsModel();
            IQueryable<AIRPORT> airports = logic.GetAll();
            vm.AirportsList = mapper.Map<IQueryable<AIRPORT>, List<Models.AirportsModel>>(airports);

        }

        private AirportsModel GetAirportsModel(int id)
        {
            AIRPORT airport = logic.GetOne(id);
            return mapper.Map<Data.AIRPORT, Models.AirportsModel>(airport);
        }

        // GET: Airports
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("AirportIndex", vm);
        }

        // GET: Airports/Details/5
        public ActionResult Details(int id)
        {
            return View("AirportsDetails", GetAirportsModel(id));
        }

        public ActionResult Delete(int id)
        {
            TempData["editResult"] = "Delete OK";
            logic.DeleteAirport(id);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedAirport = GetAirportsModel(id);
            return View("AirportIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(AirportsModel model, string editAction)
        {
            if (ModelState.IsValid && model != null)
            {
                TempData["editResult"] = "Edit OK";

                if (editAction == "AddNew")
                {
                    logic.CreateAirport(model.IATA, model.ICAO, model.FAA, model.Country, model.City);
                }
                else
                {
                    logic.UpdateFAA(model.ID, model.FAA);
                    logic.UpdateIATA(model.ID, model.IATA);
                    logic.UpdateICAO(model.ID, model.ICAO);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedAirport = model;
                return View("AirportIndex", vm);
            }
        }
    }
}

QUFLEET.Web/Views/Airports/AirportEdit.cshtml
@model QUFLEET.Web.Models.AirportsModel

<h2>Edit selected airport</h2>

@using (Html.BeginForm("Edit", "Airports"))
{
    @Html.ValidationSummary();
    @Html.AntiForgeryToken();

    @Html.HiddenFor(m => m.ID);
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">
        @Html.LabelFor(m => m.IATA);
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.IATA);
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.ICAO);
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.ICAO);
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.FAA);
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.FAA);
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.Country);
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.Country);
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.City);
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.City);
    </div>

    <input type="submit" value="SAVE" />
}

QUFLEET.Web/Views/Airports/AirportIndex.cshtml
@model QUFLEET.Web.Models.AirportsViewModel
@{
    ViewBag.Title = "AirportIndex";
}

<h2>Airports index page</h2>

<p style="color: red">@TempData["editResult"]</p>

@Html.Partial("AirportEdit", Model.EditedAirport);
@Html.Partial("Airportslist", Model.AirportsList);

QUFLEET.Web/Views/Airports/AirportsDetails.cshtml
@model QUFLEET.Web.Models.AirportsModel
@{
    ViewBag.Title = "AirportsDetails";
}

<h2>Detailed view of the airport</h2>

@Html.ActionLink("Back to the rest...", "Index");

<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.IATA)</td>
        <td>@Html.DisplayFor(m => m.IATA)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ICAO)</td>
        <td>@Html.DisplayFor(m => m.ICAO)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FAA)</td>
        <td>@Html.DisplayFor(m => m.FAA)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Country)</td>
        <td>@Html.DisplayFor(m => m.Country)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.City)</td>
        <td>@Html.DisplayFor(m => m.City)</td>
    </tr>
</table>

QUFLEET.Web/Views/Airports/AirportsList.cshtml
@model IEnumerable<QUFLEET.Web.Models.AirportsModel>

<h2>List of airports</h2>

@if (Model.Count() == 0)
{
    <p>No data available</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Country)</th>
            <th>@Html.DisplayNameFor(m => m.First().City)</th>
            <th>Datasheet</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th>@Html.DisplayFor(m => item.Country)</th>
                <th>@Html.DisplayFor(m => item.City)</th>
                <th>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</th>
                <th>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</th>
                <th>@Html.ActionLink("[DEL]", "Delete", new { id = item.ID })</th>
            </tr>
        }
    </table>
}